#!/usr/bin/env bash

set -xeo pipefail

cat bashrc >> ~/.bashrc

export PATH=$HOME/.nix-profile/bin:$PATH
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"

# nix-env -i -f ./nix --remove-all

