# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  bs-platform = nodeEnv.buildNodePackage {
    name = "bs-platform";
    packageName = "bs-platform";
    version = "4.0.14";
    src = fetchurl {
      url = "https://registry.npmjs.org/bs-platform/-/bs-platform-4.0.14.tgz";
      sha512 = "bxeMwZPnJ90r48SavF60pkzGn7heaoHn7IF7fpPdh5L8WZfCzf76AikH2zWJii4QahUeInvRN1tNPWQt3ckKJQ==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "bucklescript compiler, ocaml standard libary by bucklescript and its required runtime support";
      homepage = "https://github.com/bucklescript/bucklescript#readme";
      license = "SEE LICENSE IN LICENSE";
    };
    production = true;
    bypassCache = true;
  };
}