local legacy = require("config.theme.taste_legacy")

local M = {
  highlights = {
    { group = 'ColorColumn', fg = nil, bg = 'syntax_cursorline', attr = nil, sp = nil },
    { group = 'Conceal', fg = nil, bg = 'syntax_bg', attr = nil, sp = nil },
    { group = 'Cursor', fg = 'syntax_bg', bg = 'blue', attr = nil, sp = nil },
    { group = 'CursorIM', fg = nil, bg = nil, attr = nil, sp = nil },
    { group = 'CursorColumn', fg = nil, bg = 'syntax_cursorline', attr = nil, sp = nil },
    { group = 'CursorLine', fg = nil, bg = 'syntax_cursorline', attr = 'none', sp = nil },
    { group = 'Directory', fg = 'blue', bg = nil, attr = nil, sp = nil },
    { group = 'ErrorMsg', fg = 'red', bg = 'syntax_bg', attr = 'none', sp = nil },
    { group = 'VertSplit', fg = 'vertsplit_bg', bg = 'gutter_bg', attr = 'none', sp = nil },
    { group = 'Folded', fg = 'syntax_bg', bg = 'syntax_fold_bg', attr = 'none', sp = nil },
    { group = 'FoldColumn', fg = 'fg_dim', bg = 'chrome_bg', attr = nil, sp = nil },
    { group = 'IncSearch', fg = 'search_bg', bg = 'search', attr = 'none', sp = nil },
    { group = 'LineNr', fg = 'gutter_fg', bg = 'gutter_bg', attr = nil, sp = nil },
    { group = 'CursorLineNr', fg = 'gutter_fg', bg = 'syntax_cursorline', attr = 'none', sp = nil },
    { group = 'MatchParen', fg = 'syntax_bg', bg = 'red', attr = nil, sp = nil },
    { group = 'ModeMsg', fg = 'syntax_fg', bg = nil, attr = nil, sp = nil },
    { group = 'MoreMsg', fg = 'syntax_fg', bg = nil, attr = nil, sp = nil },
    { group = 'NonText', fg = 'syntax_bg', bg = 'syntax_bg', attr = nil, sp = nil },
    { group = 'Pmenu', fg = 'syntax_fg', bg = 'modal_bg', attr = nil, sp = nil },
    { group = 'PmenuSel', fg = 'syntax_bg', bg = 'blue', attr = nil, sp = nil },
    { group = 'PmenuSbar', fg = nil, bg = 'modal_bg', attr = nil, sp = nil },
    { group = 'PmenuThumb', fg = nil, bg = 'modal_button_bg', attr = nil, sp = nil },
    { group = 'Question', fg = 'blue', bg = nil, attr = nil, sp = nil },
    { group = 'Search', fg = 'search2_bg', bg = 'search2', attr = nil, sp = nil },
    { group = 'SpecialKey', fg = 'special_grey', bg = nil, attr = nil, sp = nil },
    { group = 'StatusLine', fg = 'syntax_fg', bg = 'chrome_bg', attr = 'none', sp = nil },
    { group = 'StatusLineNC', fg = 'chrome_bg', bg = 'chrome_fg_dim', attr = nil, sp = nil },
    { group = 'StatusLineTerm', fg = 'syntax_fg', bg = 'chrome_bg', attr = 'none', sp = nil },
    { group = 'StatusLineTermNC', fg = 'chrome_bg', bg = 'chrome_fg_dim', attr = 'reverse', sp = nil },
    { group = 'TabLine', fg = 'fg', bg = 'chrome_bg', attr = 'none', sp = nil },
    { group = 'TabLineFill', fg = 'chrome_fg_dim', bg = 'chrome_bg', attr = 'none', sp = nil },
    { group = 'TabLineSel', fg = 'blue', bg = 'syntax_bg', attr = nil, sp = nil },
    { group = 'Title', fg = 'fg', bg = nil, attr = 'none', sp = nil },
    { group = 'Visual', fg = nil, bg = 'visual', attr = nil, sp = nil },
    { group = 'VisualNOS', fg = nil, bg = 'modal_bg', attr = nil, sp = nil },
    { group = 'WarningMsg', fg = 'red', bg = nil, attr = nil, sp = nil },
    { group = 'TooLong', fg = 'red', bg = nil, attr = nil, sp = nil },
    { group = 'WildMenu', fg = 'syntax_fg', bg = 'modal_button_bg', attr = nil, sp = nil },
    { group = 'Normal', fg = 'syntax_fg', bg = 'syntax_bg', attr = nil, sp = nil },
    { group = 'Special', fg = 'blue', bg = nil, attr = nil, sp = nil },
    { group = 'Comment', fg = 'syntax_fg_dim', bg = nil, attr = 'italic', sp = nil },
    { group = 'Constant', fg = 'green', bg = nil, attr = nil, sp = nil },
    { group = 'String', fg = 'green', bg = nil, attr = nil, sp = nil },
    { group = 'Character', fg = 'green', bg = nil, attr = nil, sp = nil },
    { group = 'Number', fg = 'orange', bg = nil, attr = nil, sp = nil },
    { group = 'Boolean', fg = 'orange', bg = nil, attr = nil, sp = nil },
    { group = 'Float', fg = 'orange', bg = nil, attr = nil, sp = nil },
    { group = 'Identifier', fg = 'red', bg = nil, attr = 'none', sp = nil },
    { group = 'Function', fg = 'blue', bg = nil, attr = nil, sp = nil },
    { group = 'Statement', fg = 'purple', bg = nil, attr = 'none', sp = nil },
    { group = 'Conditional', fg = 'purple', bg = nil, attr = nil, sp = nil },
    { group = 'Repeat', fg = 'purple', bg = nil, attr = nil, sp = nil },
    { group = 'Label', fg = 'purple', bg = nil, attr = nil, sp = nil },
    { group = 'Operator', fg = 'syntax_accent', bg = nil, attr = 'none', sp = nil },
    { group = 'Keyword', fg = 'red', bg = nil, attr = nil, sp = nil },
    { group = 'Exception', fg = 'purple', bg = nil, attr = nil, sp = nil },
    { group = 'PreProc', fg = 'orange2', bg = nil, attr = nil, sp = nil },
    { group = 'Include', fg = 'cyan', bg = nil, attr = nil, sp = nil },
    { group = 'Define', fg = 'purple', bg = nil, attr = 'none', sp = nil },
    { group = 'Macro', fg = 'purple', bg = nil, attr = nil, sp = nil },
    { group = 'PreCondit', fg = 'orange2', bg = nil, attr = nil, sp = nil },
    { group = 'Type', fg = 'orange2', bg = nil, attr = 'none', sp = nil },
    { group = 'StorageClass', fg = 'orange2', bg = nil, attr = nil, sp = nil },
    { group = 'Structure', fg = 'orange2', bg = nil, attr = nil, sp = nil },
    { group = 'Typedef', fg = 'orange2', bg = nil, attr = nil, sp = nil },
    { group = 'SpecialChar', fg = nil, bg = nil, attr = nil, sp = nil },
    { group = 'Tag', fg = nil, bg = nil, attr = nil, sp = nil },
    { group = 'Delimiter', fg = nil, bg = nil, attr = nil, sp = nil },
    { group = 'SpecialComment', fg = nil, bg = nil, attr = nil, sp = nil },
    { group = 'Debug', fg = nil, bg = nil, attr = nil, sp = nil },
    { group = 'Underlined', fg = nil, bg = nil, attr = nil, sp = nil },
    { group = 'Ignore', fg = nil, bg = nil, attr = nil, sp = nil },
    { group = 'Error', fg = 'red', bg = 'syntax_bg', attr = 'bold', sp = nil },
    { group = 'Todo', fg = 'purple', bg = 'syntax_bg', attr = nil, sp = nil },
    { group = 'DiffAdd', fg = 'diff_add_fg', bg = 'diff_add_bg', attr = nil, sp = nil },
    { group = 'DiffChange', fg = nil, bg = 'chrome_bg', attr = nil, sp = nil },
    { group = 'DiffDelete', fg = 'diff_delete_bg', bg = 'diff_delete_fg', attr = nil, sp = nil },
    { group = 'DiffText', fg = nil, bg = 'modal_bg', attr = nil, sp = nil },
    { group = 'DiffAdded', fg = 'diff_add_bg', bg = 'modal_bg', attr = nil, sp = nil },
    { group = 'DiffFile', fg = 'red', bg = 'modal_bg', attr = nil, sp = nil },
    { group = 'DiffNewFile', fg = 'green', bg = 'modal_bg', attr = nil, sp = nil },
    { group = 'DiffLine', fg = 'blue', bg = 'modal_bg', attr = nil, sp = nil },
    { group = 'DiffRemoved', fg = 'red', bg = 'modal_bg', attr = nil, sp = nil },
  },
  links = {},
}

for _, highlight in ipairs(legacy.highlights) do
  table.insert(M.highlights, highlight)
end

for _, link in ipairs(legacy.links) do
  table.insert(M.links, link)
end

return M
