# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  now = nodeEnv.buildNodePackage {
    name = "now";
    packageName = "now";
    version = "12.1.11";
    src = fetchurl {
      url = "https://registry.npmjs.org/now/-/now-12.1.11.tgz";
      sha512 = "KIWmczCUuEXUYEYYMLSPaZ5gwqjpgboraBbl8BVSW3C9bZwXjw0j/3SVXXZqJ0sTLbCZli+OuRDjZqBWqbWtwA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "The command-line interface for Now";
      homepage = "https://github.com/zeit/now-cli#readme";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
  };
}