# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  now = nodeEnv.buildNodePackage {
    name = "now";
    packageName = "now";
    version = "13.1.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/now/-/now-13.1.2.tgz";
      sha512 = "v6K4141Zcw/EsEC88uQ8DusP5LnbLIYFEblpH9BiQXCx4s4qmk56xxT7AXRCFBMtUFTX0hF8Bd2rqWGs0HzjAQ==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "The command-line interface for Now";
      homepage = "https://github.com/zeit/now-cli#readme";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
  };
}