# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  now = nodeEnv.buildNodePackage {
    name = "now";
    packageName = "now";
    version = "15.1.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/now/-/now-15.1.0.tgz";
      sha512 = "j43YCZvBR2upKjaC7l+po970BMxYK+PuxLlrb9kJ2/YkQ0OtkIgXrkpCmRBOj/h356X7Jfuw2DX45gHfc1rx2w==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "The command-line interface for Now";
      homepage = "https://github.com/zeit/now-cli#readme";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
  };
}