# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  lumo-cljs = nodeEnv.buildNodePackage {
    name = "lumo-cljs";
    packageName = "lumo-cljs";
    version = "1.10.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/lumo-cljs/-/lumo-cljs-1.10.1.tgz";
      sha512 = "pqgygbEEnzOjFUxejr/jK7gRhuQx0acd3PLyJwkz4ZyVHWyzGGhUxwzgYX/df4wKm7Zixfp73G0S0PFXiNHULQ==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Fast, cross-platform, standalone ClojureScript REPL";
      homepage = https://github.com/anmonteiro/lumo;
      license = "EPL-1.0";
    };
    production = true;
    bypassCache = true;
  };
}