# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  lumo-cljs = nodeEnv.buildNodePackage {
    name = "lumo-cljs";
    packageName = "lumo-cljs";
    version = "1.9.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/lumo-cljs/-/lumo-cljs-1.9.0.tgz";
      sha512 = "C7sM26P7bBtrAz+pW1TlkjIUXcYHmE3oENQLVe4GsYbX0ePJB4w0KK7Tm0WxVREGMllTcNlDJLqz30/W9vud0A==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Fast, cross-platform, standalone ClojureScript REPL";
      homepage = https://github.com/anmonteiro/lumo;
      license = "EPL-1.0";
    };
    production = true;
    bypassCache = true;
  };
}